version: '2'

services:
  drone-server:
    image: drone/drone:0.7
    ports:
      - 80:8000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=192.168.99.100
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=090e76294f2dd7220768
      - DRONE_GITHUB_SECRET=aebc51f0aa7188c94600010ef92402b8454663f4
      - DRONE_SECRET=dronesecret
      - DRONE_ADMIN=nguyentantu

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=dronesecret